### ISSUE TITLE
I want to save received data from gxradar

### ISSUE THREAD

**Issue by Xeriou** [trudK45/gxradar_pi#7]
Hello,

In recent project needed, I want to save received data from gxradar
where can I modify in code ?
I'm a C++ newbie, so I need your suggestion 
can you help me ?
(I'm not very good at English, so if some words are impolite, i did not mean to....)

**Comment by trudK45** [comment]
I am not sure what you mean when you say you want to save received data from gxradar.
Do you mean the ethernet data coming from the radar dome ?
To modify the code you will have to fetch it from github and set up an environment for building the code as described here [https://github.com/trudK45/gxradar_pi](url)

**Comment by Xeriou** [comment]
Hello,
Yes, I found the gxradar_pi project, and I want to save data to disk when program receive data from the radar dome. 
Here is my thought. I want to inject the "save data" code after a full information of object is complete (in the code, maybe process many packet already...)
so, can you help me that which part can I start it ?

**Comment by Xeriou** [comment]
well,   I read the code several days.
now i got it :P
please close this issue ~

**Comment by trudK45** [comment]
You may be interested to know that this code will be obsolete in a near future. I have teamed up with the Navico guys and we are in the process of integrating the Garmin xHD and Garmin HD radar into a common front end supporting many different radars. You can even run several different radars simultaneously. There will be guard zones with much better false alarm sustainability. ARPA fully integrated.

**Comment by Xeriou** [comment]
Yeh , I have noticed https://github.com/opencpn-radar-pi/radar_pi
and i will keep track on this :P ~

Actually, what the requirement I only need is just add some "filestream code" (save radar to file) into about line 1602 in gx_radar_pi.cpp( before drawing triangle)
In my case, i need to save data at the sea, and replay radar data in the lab
and for now, I only have Garmin xHD radar so far.
